name: ASN√ÅRIO
favicon: null
layout_spectrum: 0.37083
typography_spectrum: 0.25312
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 0.13118391018360853
  saturation: 0.29511270415969193
  rhythmicContrast: 0.7788866115733981
purpose: []
